### ISSUE TITLE
Add seeds / peer info to torrent list.

### ISSUE THREAD

**Issue by AnthonyBloomer** [AnthonyBloomer/ezflix#10]

**Comment by jatinkrmalik** [comment]
Can I work on this one? I am trying to start my Github journey. :)

**Comment by AnthonyBloomer** [comment]
That'd be great. Let me know if you have any questions regarding the code I have there but this should be pretty straight forward to do!

**Comment by jatinkrmalik** [comment]
I have raised a pull request. Please review the code.
