### ISSUE TITLE
EZTV API

### ISSUE THREAD

**Issue by AnthonyBloomer** [AnthonyBloomer/ezflix#15]
EZTV API is in beta mode and does not require an API Login or API key. 

Request: ```https://eztv.ag/api/get-torrents```
Parameters: limit (results per page, between 1 and 100); page (current page of results) 

Example request: ```https://eztv.ag/api/get-torrents?limit=10&page=1```

Show lookup by IMDB ID

If you already know a show's IMDB ID, you can use this endpoint to find only the torrents for this exact show on EZTV. If the given ID can be matched, all its EZTV torrents will be returned. 

Example request: ```https://eztv.ag/api/get-torrents?imdb_id=6048596```

Results are returned in JSON format.

https://eztv.ag/api/

This may be useful to implement in the future.

**Comment by santiagoeibarra** [comment]
There is a way to determine the ID inside eztv? Por example the stargate atlantis ID in imdb is 0374455 but when I made a request
 data = requests.post('https://eztv.io/api/get-torrents?0374455')

I got the homepage list, not the stargate atlantis list
