### ISSUE TITLE
peerflix takes 5 positional args, 6 were given

### ISSUE THREAD

**Issue by asheroto** [AnthonyBloomer/ezflix#22]
LOVE the project.  Have an error, though...

`ezflix "South Park" --latest`

`In ezflix, the default player is mpv. It will fallback to vlc if mpv isn't found. You can use the media_player argument to set your media player.
Playing South Park S23E10 Christmas Snow UNCENSORED 720p WEB-DL AAC2 0 H 264-LAZY EZTV
Traceback (most recent call last):
  File "/usr/local/bin/ezflix", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/ezflix/main.py", line 39, in main
    search(p)
  File "/usr/local/lib/python3.7/dist-packages/ezflix/main.py", line 139, in search
    peerflix(latest['link'], media_player, args.media_type, args.subtitles, args.remove, file_path)
TypeError: peerflix() takes 5 positional arguments but 6 were given
`

**Comment by AnthonyBloomer** [comment]
Hello @asheroto,

Thanks for the nice feedback! I did spot this error a while back and it was fixed. I've pushed [v1.6.4](https://pypi.org/project/ezflix/1.6.4/) to PyPi. Could you try this version? Please let me know if you're still running into issues. 

```
pip install ezflix==1.6.4
```
