### ISSUE TITLE
webplay spams console

### ISSUE THREAD

**Issue by asheroto** [AnthonyBloomer/ezflix#23]
I did

` ezflix "South Park" --media_player webplay`

and selected 1, and the console screen continuously spams the same message over and over again, impossible to end.

**Comment by AnthonyBloomer** [comment]
Hello @asheroto, when I was building this I saw that Peerflix had support for Webplay so included it in the supported media players. Could you please provide a link to the Webplay project so I can test here? Thanks!

**Comment by AnthonyBloomer** [comment]
Related issue: https://github.com/mafintosh/peerflix/issues/304

**Comment by AnthonyBloomer** [comment]
Closing.
