### ISSUE TITLE
Getting UnboundLocalError in main.py

### ISSUE THREAD

**Issue by jatinkrmalik** [AnthonyBloomer/ezflix#9]
Hi @AnthonyBloomer,

I think this is a fantastic project, and something similar to what I was planning to build in my free time. I tried to install ezflix via pip3 and tried executing the `ezflix movie 'spiderman'` which did print a list of matching movies but failed with the following exception. I looked into the code and I think it was something to do with your py2/py3 compatibility code somewhere here - https://github.com/AnthonyBloomer/ezflix/blob/2445ed8a926c1c83c280732688362d0b1880dd0e/ezflix/main.py#L53

Anyways here is the error stack:

> _Make selection: (Enter quit to close the program)
> Traceback (most recent call last):
>   File "/usr/local/bin/ezflix", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.6/site-packages/ezflix/main.py", line 70, in main
>     read = input()
> UnboundLocalError: local variable 'input' referenced before assignment_
>

**Comment by AnthonyBloomer** [comment]
Hi @jatinkrmalik,

Glad you like the project and thank you for raising this issue. I have fixed the error. A new version of ezflix is now available on PyPi.
